### ISSUE TITLE
The $dbic_handles{$pid_tid} trick does not make sence

### ISSUE THREAD

**Issue by hvoers** [interchange/Dancer2-Session-DBIC#15]
If it's really needed **ALL** users of Dancer{|2}::Plugin::DBIC should implement it.
You have to trust the object returned by DBICx::Sugar::schema($name)

Shel I make a PR to remove this?

**Comment by racke** [comment]
Yeah I agree. This trick predated usage of DBICx::Sugar in DBIC plugin.

**Comment by hvoers** [comment]
Okay. The pid_tid trick is gone and the hash is a scalar, but still global. :(
I will keep this in mind.
Maybe I must hack on DBICx::Sugar first.

**Comment by racke** [comment]
Maybe we can store it in an accessor?
