### ISSUE TITLE
Every request generates a new session if id_column and data_column are set to 'id' & 'data'

### ISSUE THREAD

**Issue by roryzweistra** [interchange/Dancer2-Session-DBIC#9]
When I have set the config to:
```
resultset: "Session"
id_column: "id"
data_column: "data"
```
I end up with a new session on every request. You can see below how it does try to find the session but one way or another something happens that triggers a new session lookup.

request 1
```
SELECT me.id, me.data, me.modified FROM session me WHERE ( me.id = ? ): 'Vuql_trKPLdofGSTKODNQoaops0sSNWX'
INSERT INTO session ( data, id) VALUES ( ?, ? ): '{}', 'Vuql_trKPLdofGSTKODNQoaops0sSNWX'
```
request 2
```
SELECT me.id, me.data, me.modified FROM session me WHERE ( me.id = ? ): 'Vuql_trKPLdofGSTKODNQoaops0sSNWX'
SELECT me.id, me.data, me.modified FROM session me WHERE ( me.id = ? ): 'VuqmABEiaCcA9JRveJ9LTApFMV2c2N_A'
INSERT INTO session ( data, id) VALUES ( ?, ? ): '{}', 'VuqmABEiaCcA9JRveJ9LTApFMV2c2N_A'
```
request 3
```
SELECT me.id, me.data, me.modified FROM session me WHERE ( me.id = ? ): 'VuqmABEiaCcA9JRveJ9LTApFMV2c2N_A'
SELECT me.id, me.data, me.modified FROM session me WHERE ( me.id = ? ): 'VuqmBpEkUo303zUZWtR3mXwGOzayFLH4'
INSERT INTO session ( data, id) VALUES ( ?, ? ): '{}', 'VuqmBpEkUo303zUZWtR3mXwGOzayFLH4'
```
etc....

The data is inserted in the table so that part works fine.
```
+----------------------------------+------+---------------------+
| id                               | data | modified            |
+----------------------------------+------+---------------------+
| VuqemLa3fltU4HCmh1C4xA9qMLR2HX1g | {}   | 2016-03-17 12:10:01 |
| VuqerdzZSrEzcZC3lA2_cE94G3Y0DYyn | {}   | 2016-03-17 12:10:21 |
+----------------------------------+------+---------------------+

```

Now if I set the config to the default:
```
resultset: "Session"
id_column: "sessions_id"
data_column: "session_data"
```

Everything works like expected.

request 1
```
SELECT me.sessions_id, me.session_data, me.modified FROM session me WHERE ( me.sessions_id = ? ): 'Vuqe_BJnilZGVuMGcvl73pQt8B7lgzev'
```
request 2
```
SELECT me.sessions_id, me.session_data, me.modified FROM session me WHERE ( me.sessions_id = ? ): 'Vuqe_BJnilZGVuMGcvl73pQt8B7lgzev'
```
request 3
```
SELECT me.sessions_id, me.session_data, me.modified FROM session me WHERE ( me.sessions_id = ? ): 'Vuqe_BJnilZGVuMGcvl73pQt8B7lgzev'
```

**Comment by SysPete** [comment]
@roryzweistra were you testing against latest CPAN release or against current GitHub master branch? I've been fixing issues with master today and have converted one test to using id/data and it works fine.

**Comment by roryzweistra** [comment]
I meant to do more debugging over the weekend but my kids we're thinking otherwise.

I was testing with Dancer2-Session-DBIC-0.007 in a Carton setup. 
If you need more info please let me know, I'll try to do some more debugging myself.

**Comment by SysPete** [comment]
I'd really appreciate if you could try latest master branch in GH since this has tests that specifically use `id` and `data` as column names.

**Comment by racke** [comment]
The fix is part of release 0.100, which went into CPAN this morning.

**Comment by roryzweistra** [comment]
Successfully installed Dancer2-Session-DBIC-0.102 (upgraded from 0.007)

Finally had some time to try the new version and it works like a charm!

**Comment by racke** [comment]
Excellent, thanks for your feedback!
